; Auto-generated. Do not edit!


(cl:in-package roomba_500_series-msg)


;//! \htmlinclude GoDockResult.msg.html

(cl:defclass <GoDockResult> (roslisp-msg-protocol:ros-message)
  ((dock
    :reader dock
    :initarg :dock
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GoDockResult (<GoDockResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoDockResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoDockResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roomba_500_series-msg:<GoDockResult> is deprecated: use roomba_500_series-msg:GoDockResult instead.")))

(cl:ensure-generic-function 'dock-val :lambda-list '(m))
(cl:defmethod dock-val ((m <GoDockResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roomba_500_series-msg:dock-val is deprecated.  Use roomba_500_series-msg:dock instead.")
  (dock m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoDockResult>) ostream)
  "Serializes a message object of type '<GoDockResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'dock) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoDockResult>) istream)
  "Deserializes a message object of type '<GoDockResult>"
    (cl:setf (cl:slot-value msg 'dock) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoDockResult>)))
  "Returns string type for a message object of type '<GoDockResult>"
  "roomba_500_series/GoDockResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoDockResult)))
  "Returns string type for a message object of type 'GoDockResult"
  "roomba_500_series/GoDockResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoDockResult>)))
  "Returns md5sum for a message object of type '<GoDockResult>"
  "035360b0bb03f7f742a0b2d734a3a660")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoDockResult)))
  "Returns md5sum for a message object of type 'GoDockResult"
  "035360b0bb03f7f742a0b2d734a3a660")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoDockResult>)))
  "Returns full string definition for message of type '<GoDockResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool dock~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoDockResult)))
  "Returns full string definition for message of type 'GoDockResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool dock~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoDockResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoDockResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoDockResult
    (cl:cons ':dock (dock msg))
))
